POST http://localhost:3000/upload/single
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="02.jpg"
Content-Type: image/*

< ../../imgs/02.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--